### ISSUE TITLE
error when trying to create a second ticketmenu

### ISSUE THREAD

**Issue by ClaraCrazy** [Fear-and-Terror-EU-Programming-Team/fear-and-terror-ticket-bot#4]
Hey. So I encountered an error when trying to add a second ticketmenu:

```
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 343 , in _run_event
    await coro(*args, **kwargs)
  File "ticket_bot.py", line 48, in on_raw_reaction_add
    await emoji_handlers[rp.emoji.name](rp)
  File "ticket_bot.py", line 67, in create_ticket
    game_name = re.match(pattern, title).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Any ideas? So far I only had one so I never noticed this
This happens when trying to click the emote that creates a help-channel for me

**Comment by w4rum** [comment]
Seems like the regex didn't match. That's odd since the pattern is applied to the title of the first embed of the message, which is created by the bot itself. I don't really habe the time to debug any of this. You might want to try to reproduce it in a debug environment and step through the `create_ticket` function. Maybe it's looking at the wrong message for some reason.
